### ISSUE TITLE
ASIO plugin appears to force ASIO device into 44.1KHz, even though OBS is set to 48KHz.

### ISSUE THREAD

**Issue by polyh3dron** [Andersama/obs-asio#102]
1. Without OBS open, set ASIO device to 48 KHz
2. Open a blank OBS instance, create an ASIO Audio source and select your ASIO audio device
3. Watch as your device's sample rate is changed to 44.1KHz, even if OBS's audio is set to 48KHz

Please allow for 48KHz to be used with ASIO.

**Comment by polyh3dron** [comment]
This appears to only be happening when also using Voicemeeter to enable virtual outputs to my ASIO device, since even with this ASIO plugin, we cannot set outputs with it. So if I have Voicemeeter open with my ASIO device selected as its hardware output at 48 KHz, and then I open OBS with an ASIO input source selected with that same device, the input device will not work. From the description of this plugin I was led to believe other apps would be able to access an ASIO device, but is this not the case? As it is, this plugin renders my ASIO device's outputs useless since I cannot assign them in OBS, and I cannot run Voicemeeter with my ASIO device in an attempt to set virtual WDM outputs that than get sent to ASIO outputs in Voicemeeter.

**Comment by Andersama** [comment]
The plugin is setup to be quick and easy to use, so it tries to query the device for its current settings so it won't force the device to update anything. Resampling should be handled by obs, so you don't have to worry about a sample rate mismatch (although ideally you don't have any resampling).

If you're looking to capture an output channel you'll have to do a bit of a work around see #87

**Comment by polyh3dron** [comment]
Seems like the sample rate changing was caused by me attempting to access my ASIO device with another piece of software simultaneously (Voicemeeter) that actually can use the outputs. I must be stuck on the odd terminology you are using about outputs because when you talk about "capturing" an output, I'm thinking you are talking about looping an output back into OBS and that is not at all what I am trying to do with OBS. I have been trying to **use** my ASIO outputs with OBS, as in, output audio from OBS to my ASIO outputs. I have given up on this and have invested time and money into Voicemeeter and VBAN as an alternative for multichannel surround I/O and acting as a front end for my ASIO device on both PCs. Only being able to use ASIO inputs without outputs is quite crippling.

**Comment by Andersama** [comment]
Ah, ok, then now I get what you're after, this plugin's about getting audio from asio to record etc. Never got around to making the complementary plugin. There wasn't a lot of motivation because there's already monitoring etc for sending audio out.

**Comment by polyh3dron** [comment]
By now I have seen a strong sentiment from a few OBS devs that they do not, under any circumstance, want to make OBS a DAW, and that the features I am looking to have with OBS fall under this. All I'm trying to do in this instance is monitor the entire in 5.1 surround with my ASIO audio interface, and send out a few additional 5.1 signals for live monitoring to mix in with my source audio. Audio Monitor works perfectly for this with WDM devices, but for something professional with lower latency and higher channel count, it's usually ASIO.
