### ISSUE TITLE
Issue with ASIO UX2

### ISSUE THREAD

**Issue by TenaciousLemur** [Andersama/obs-asio#116]
Before posting an Issue, make sure that:
- you've read the wiki especially the Install and Usage section, the Troubleshooting section, the Capturing mixes section.
- you've researched the issues to find if there aren't similar issues which have been posted already.
- have an obs log ready (obs-studio : help menu > log > see current log)

**Plugin Version**
3.10

**Describe the bug**
When using my Line6 POD studio UX2, I have to use the UX2 ASIO driver to get the guitar input to come through into the DAW, at least on the POD farm plugin. I have ASIO4all which doesn't let me change the sample rate and RealtekASIO which doesn't seem to get any audio input. The frustrating thing is that no options come up to allow me to try to work around it using stuff like ReaStream. If I don't really know what's going on or why there are a million different ASIO drivers. Essentially I am wondering if it's the plug-in's issue that means it doesn't detect the UX2 audio interface or if it's fundamentally how that system works.

[OBS_log_28062022.txt](https://github.com/Andersama/obs-asio/files/8998598/OBS_log_28062022.txt)

**To Reproduce**
1. Go to add ASIO input
2. Click on the device dropdown and select the ASIO UX2 device
3. Select Stereo
4. Both channels only list the mute option

**Expected behavior**
I expected to be able to send audio from bitwig studio to OBS while using my POD studio UX2 interface

**Screenshots**
![image](https://user-images.githubusercontent.com/81366227/176120148-eea9724c-8282-493d-b1ad-3493cde0ffd1.png)

**Additional context**
I apologise if this is too broad or not really solvable, I just thought I'd ask the pros.

**Comment by TenaciousLemur** [comment]
Hi, I have found a workaround using ReaStream. I appreciate your response on this a lot. You can mark it closed if you like.

Basically what you suggested ^_^

**Comment by Andersama** [comment]
No problem, I know it's a bit silly to have to use work arounds, but that's how it is with asio drivers. Glad it works.
