### ISSUE TITLE
Plug-in DOES NOT SAVE SETTINGS

### ISSUE THREAD

**Issue by LyranGod** [Andersama/obs-asio#117]
Every time I open OBS for a new stream I am dealing with the problem that I have to go back into the control panel and reset the buffer settings. This is a consistent thing every single time I open the program. Nothing ever saves inside the control panel, and after applying the same settings probably 100s or even 1000s of times Ive decided to bring this to the devs, as it is an extreme hassle. especially if you forget about it start a stream, and have to fix the audio during a stream. Most times it crashes the drivers and you have to restart the entire stream again.

**Comment by Andersama** [comment]
The Juce version of the plugin is setup to connect to the device with it's reported current settings. You may want to try the older version which behaves more like a daw and has the plugin try to control the device settings. I'm assuming of course you're using the newest Juce version. In any case there's not much I can do about device drivers being unstable.
