### ISSUE TITLE
Need to send source output to mix table via ASIO

### ISSUE THREAD

**Issue by MatDepInfo** [Andersama/obs-asio#118]
Hello,
I got a Presonus 32SC. Thanks to this device, I can send all my channel to OBS via Asio Input. But I want that all of my OBS sources with audio are send to the Presonus to mix them into external speaker connected to the Presonus and to send the mix to OBS too. I try the Audio Monitor plugin but I can only send audio source output via WMZ (only 3 outputs...). Is it possible to have a mix of Asio plugin and this one ? Or another idea ?

**Comment by Andersama** [comment]
The plugin is not setup to do monitoring, it'd be possible to edit the plugin to handle monitoring, but I'm not particularly motivated to. Sorry, you'll have to find a work around.
