### ISSUE TITLE
on  OBS 29.x  no audio on recorded video when 2.1 channel is used.

### ISSUE THREAD

**Issue by tormyvancool** [Andersama/obs-asio#134]
**Plugin Version**
The most recent one released in 2022

**Describe the bug**
I described the bug here: 
https://github.com/obsproject/obs-studio/issues/8225
thinking it was due OBS. After investigations, @pkviet concluded that the issue is due ASIO plugin.
Hence I'm reporting here.

**To Reproduce**
Setup everything like in the video here 
https://youtu.be/FCFXxQf-s6s
The use case in this video is what is needed.

It worked super-fine till version 28.1.2 of OBS included.
Since version 29.x, the audio is not recorded. The recorded video is fully muted.
But using configurations like: Mono/Stereo/5.1/7.1 etc: it works fine.
Only with the 2.1 (needed in this Use Case) it's muted :-/

**Expected behavior**
I expect that, as it was for 28.1.2, when I record the video also the audio is recorded.

**Additional context**
Log OBS: https://obsproject.com/logs/yCKmYwfFwaZCf07j

**Comment by Andersama** [comment]
Wizard's going to look into it, but if you're able, fork the repo and rebuild it against v29. I suspect there's been an api break see if your rebuilt one works. If not let us know.

**Comment by Andersama** [comment]
Talking with Wizard it's sort've what I pictured happening. There was a breaking change in OBS, funnily enough it sounds like it had to do with surround sound support which is what pkv worked on right before we started on the asio plugin. It all comes back around. I'm sure there'll be a patch, wait a bit and the plugin should work again.

**Comment by tormyvancool** [comment]
> Talking with Wizard it's sort've what I pictured happening. There was a breaking change in OBS, funnily enough it sounds like it had to do with surround sound support which is what pkv worked on right before we started on the asio plugin. It all comes back around. I'm sure there'll be a patch, wait a bit and the plugin should work again.

yes right. Indeed today, after have read you and PKV, I tried to remove the ASIO drivers (at the end it was ok) and I verified that on the 2.1 however OBS is failing ... it's urge to have the 29.0.3 asap.
Thank you for your Collaboration and Understanding. I appreciated.

**Comment by Andersama** [comment]
To be fair, I have the advantage, my code's not changing, so when things stop working after a version change. Unless by some weird quirk where an reveals a bug in my code, there's really only one direction it points. Definitely funny that a version change would break things right after I wrote something to talk about why the semantic versioning system can trip people up for exactly this type of reason. Although from what I've been told it's to do with an update to ffmpeg and I'm not sure that I'd have categorized that as a `major` change...but that just goes to show that any version update could break things.

**Comment by tormyvancool** [comment]
> To be fair, I have the advantage, my code's not changing, so when things stop working after a version change. Unless by some weird quirk where an edit reveals a bug in my code, there's really only one direction it points. Definitely funny that a version change would break things right after I wrote something to talk about why the semantic versioning system can trip people up for exactly this type of reason. Although from what I've been told it's to do with an update to ffmpeg and I'm not sure that I'd have categorized that as a `major` change...but that just goes to show that any version update could break things.

I think that at any version change, everything should be tested up. But that "everything" is damn high number of things ... 'cause ti should be done before official release ...
