### ISSUE TITLE
OBS V29 - cannot add new inputs

### ISSUE THREAD

**Issue by jasonseeb** [Andersama/obs-asio#140]
I cannot add new inputs in OBS 29.1.3. I don't know how far back it goes, but I do know it works fine on the last version of 28. I only found the issue because I built a new PC for streaming and it did not work.

I then realized my older PC with OBS v29.1.3 has the scenes with asio inputs added and they work fine. Then I found out I cannot add inputs on that PC either. It seems as if the asio inputs that were added from an earlier version of OBS, where the plugin works, carry over to the new installation.

I only chose version 28 to go to because someone posted it worked for them in the discussion forums. When I get time I'll officially test with what version the plugin stops working properly.

**Comment by antarex-be** [comment]
Same problem with OBS 30.0.0 : after adding an ASIO source, unable to select the OBS Channel (even after reopening the settings UI like before).

Currently to use it : i add my ASIO sources in my scenes, i close OBS, i modify the collection JSON file (with a text editor), then i reopen OBS.  With this method, i'm still unable to see the channels numbers in the OBS UI, but the ASIO input is working.

**Comment by whentotrade** [comment]
Same issue; no way to select channels. I needed to roll back to 28.1.2. thanks @antarex-be for the possible workaround with modifiing JSON manually; need to try next time.

**Comment by DenisKruglik** [comment]
I also face this issue with version 30.0.0

**Comment by Aleskis** [comment]
Same problem here

**Comment by Aleskis** [comment]
@antarex-be, in the collection json, I don't find the parameter corresponding to channel. Can you tell how it names please ? Thank you !

**Comment by DapperMickie** [comment]
https://github.com/foxx1337/obs-asio/releases/tag/v3.2.0-bassasio
Someone made a fork of this repo and made a fix.
Download the 7z file and extract it to the root folder of your obs-studio installation.
Should be something like "C://Program Files/obs-studio".

This fix works for obs-studio 30, not sure about 29.

**Comment by Aleskis** [comment]
OH YES ! Thanks it works perfectly.

**Comment by jasonseeb** [comment]
It will be great to try this when I'm back from vacation

**Comment by nemrcomedy** [comment]
Hi I found this thread while also looking for a fix for the ASIO plugin no longer working with OBS 30. If I roll back to 29 it works as it did no issue, but for V30 no luck. I tried this fix it doesn't work for me. When I try to open the properties box obs freezes and I have to force quit.

Has anyone had any luck with this working with OBS 30 specifically? Am I missing a step possibly? I replaced the files in their corresponding folders completely

> https://github.com/foxx1337/obs-asio/releases/tag/v3.2.0-bassasio Someone made a fork of this repo and made a fix. Download the 7z file and extract it to the root folder of your obs-studio installation. Should be something like "C://Program Files/obs-studio".
> 
> This fix works for obs-studio 30, not sure about 29.

**Comment by jasonseeb** [comment]
> Hi I found this thread while also looking for a fix for the ASIO plugin no longer working with OBS 30. If I roll back to 29 it works as it did no issue, but for V30 no luck. I tried this fix it doesn't work for me. When I try to open the properties box obs freezes and I have to force quit.
> 
> Has anyone had any luck with this working with OBS 30 specifically? Am I missing a step possibly? I replaced the files in their corresponding folders completely
> 
> > https://github.com/foxx1337/obs-asio/releases/tag/v3.2.0-bassasio Someone made a fork of this repo and made a fix. Download the 7z file and extract it to the root folder of your obs-studio installation. Should be something like "C://Program Files/obs-studio".
> > This fix works for obs-studio 30, not sure about 29.

I am the op and yes it has worked for me on 2 different PCs with 2 different audio interfaces (behringer and presonus). I'm not home at the moment to follow along with what you did but I can offer some assistance once I am.

**Comment by nemrcomedy** [comment]
Oh man @jasonseeb that would be awesome if you could. I'm using UAD Apollo as an audio interface. What I did was download the obs-asio.v320-bassasio.7z file. Extract its contents and then:

1. Overwrite the en_US file from obs-asio.v320-bassasio\data\obs-plugins\obs-asio\locale to C:\Program Files\obs-studio\data\obs-plugins\obs-asio\locale

2. Overwrite all the files from obs-asio.v320-bassasio\obs-plugins\64bit (obs-asio.dll, obs-asio.pdb, get-bassasio, bassasio.dll) to C:\Program Files\obs-studio\obs-plugins\64bit

Previously I had been using the obs-asio-3.1.1-windows-x64-Installer to install the plugin in every verion up to 29 where it worked fine. So I never actually copy and pasted files or anything. But I read this was the way to do that? Thank you so much for offering to help! Please let me know if you need any other info!

**Comment by jasonseeb** [comment]
@nemrcomedy Sorry about the delay. You have the files in the right place.

After adding the source you should get the ability to add an "asioInput" which looks like this:
![1](https://github.com/Andersama/obs-asio/assets/134801575/0cdc13e7-7dde-4fb1-af16-ee4a154a22eb)

I then select my asio driver and then click the ASIO driver control panel button like this:
![2](https://github.com/Andersama/obs-asio/assets/134801575/41e4a5c2-59fb-4846-abb9-62b15534bac8)

It then fills in the blank spaces and I am able to select the options I want:
![3](https://github.com/Andersama/obs-asio/assets/134801575/1aad7d39-e2be-4625-8cc3-72fe218e5636)
![4](https://github.com/Andersama/obs-asio/assets/134801575/35de5e6d-7eb2-49db-8380-7a43db711dd6)

I know I had to restart my PC because my other Behringer driver was not picking up correctly the first time. I would also make sure the buffersize(sometimes called blocksize) is matching. I think that might have been the reason I had to restart because my Behringer needed to before it would set correctly.

**Comment by Malumen** [comment]
**Doesn't work for me.** 

Series 208i (tascam). I can load this software into OBS, it does what you show in the images @jasonseeb but I get no audio from my device. Lists 20 inputs (as it has 20 digital inputs, 4 of which are real mic inputs). I tried all of them, no audio input. :(

**Comment by jasonseeb** [comment]
@Malumen
I don't know what to do from here. Maybe restart the PC if you haven't already. I wish I could help you but I'm not the creator of the original obs_asio or the fork obs_bassio. If I find the time I might come up with my own plugin in the future.

**Comment by nemrcomedy** [comment]
> When you say you have been using this for a couple of years, do you mean the obs-asio or obs-bassio fork? If you were using the original, I would recommend removing the obs-asio completely.
> 
> Other than that, good luck! Anymore questions, ask away and I'll answer what I can.

Thank you for all your help thus far! I ran add/remove programs in windows and uninstalled obs-asio 3.1.1 and then did the obs-bassio fork but I am still getting the same result of obs freezing when I try to open the properties option.

I can't find anything online about completely removing obs-asio do you by any chance know if I'm missing anything from doing that effectively?

**Comment by nemrcomedy** [comment]
I now went into the plugins folder and deleted anything asio related and I don't get the option to add an asio input anymore so I know I removed everything. I then followed the steps to install the fork and I'm still getting a frozen obs when I add an asio input :/

**Comment by nemrcomedy** [comment]
No joke, could I pay you to write that plug in? I'm not kidding name your
price I will pay you in advance and make it free to the public. It's insane
how difficult it is to get this going!

**Comment by jasonseeb** [comment]
I'll see what I can do. I'll keep you updated.

**Comment by nemrcomedy** [comment]
OK please let me know I would be happy to pay for it I know the community
needs it!

**Comment by jasonseeb** [comment]
@nemrcomedy, please let me know if that fix works for you. I was going to start looking into a new plugin, but I just saw this added by the developer of obs-asio. If it doesn't, I can still look into it myself. I'm sure @pkviet has a head start and can more easily fix the original.

@pkviet I can be a tester as I stream 1-2 times daily for about 6-8hrs. Just let me know if you need anything other than reporting any problems here.

**Comment by nemrcomedy** [comment]
So I just installed this! And it looks like it is working perfectly on my end! Thank you SO MUCH @pkviet you are a real one! I will stream soon and update if anything goes wrong but so far so good offline!

**Comment by pkviet** [comment]
> So I just installed this! And it looks like it is working perfectly on my end! Thank you SO MUCH @pkviet you are a real one! I will stream soon and update if anything goes wrong but so far so good offline!

Nice. Check whether it crashes on exit. I've had a report it could crash but the last build has a temptative fix.

**Comment by whentotrade** [comment]
Thank you @pkviet ! I installed and it looks like everything is working. I will have a longer OBS session tomorrow with intense audio usage. So I can report back tomorrow after some more testing.

**Comment by pkviet** [comment]
> Thank you @pkviet ! I installed and it looks like everything is working. I will have a longer OBS session tomorrow with intense audio usage. So I can report back tomorrow after some more testing.

please post feedback here: https://github.com/pkviet/obs-asio/discussions/2 rather than in this closed Issue. Thanks.

**Comment by pkviet** [comment]
I've pushed a fix on v3 here:
https://github.com/Andersama/obs-asio/releases/tag/v3.2.0
I'm putting aside v4 for the time being, so the releases for v4 won't be available anymore on https://github.com/pkviet/obs-asio/releases.
