### ISSUE TITLE
Crash on OBS 30.0.2 when device disconnects

### ISSUE THREAD

**Issue by duncte123** [Andersama/obs-asio#147]
**Plugin Version**
v3.2.0

**Describe the bug**
When an ASIO device that is in use disconnects (simulated by unplugging it) due to any number of reasons the plugin crashes OBS.

Crash log: https://obsproject.com/logs/RsyQnlhGj0HVHmhJ
OBS log: https://obsproject.com/logs/dOgbHDInPwItI1zf

**To Reproduce**
1. Use your favourite ASIO interface
2. Have it disconnect (unplugging works for me)
3. OBS crashes

**Expected behavior**
I would expect the plugin to notice the device has disappeared and stop using it. After a connection to the device has been established again, I would expect the plugin to pick it up and continue like nothing happened.

**Screenshots**
![image](https://github.com/Andersama/obs-asio/assets/8843386/0d5cd45f-82a1-4690-a234-140e7325a13f)
![image](https://github.com/Andersama/obs-asio/assets/8843386/6447cc89-f9ac-4485-b35b-bc77e031584e)
![image](https://github.com/Andersama/obs-asio/assets/8843386/df616fa2-f85f-4670-b9e8-462e2077ed70)
![image](https://github.com/Andersama/obs-asio/assets/8843386/1faee9ad-a457-487a-a1bb-b8e80b8bb205)
![image](https://github.com/Andersama/obs-asio/assets/8843386/597075e0-5335-4d3f-828e-a4ed548e8d43)
![image](https://github.com/Andersama/obs-asio/assets/8843386/53d0f4db-7711-43be-a64c-7a155c815b7d)

**Additional context**
I have a compressor and a limiter filter enabled for the source.

The USB connection on my audio interface is not the most reliable, if I accidentally touch the cable the device will disconnect for a few ms and continue working normally afterwards. WASAPI also struggles with this. Windows would still see the interface but will not allow any audio to go from and to it until I disconnect and reconnect it.

**Comment by Andersama** [comment]
When you replicate the error, can you check in your logs for a line that starts with `Device Error`.
I don't believe I've ever intentionally unplugged my devices in testing.

**Comment by duncte123** [comment]
[2024-05-23 08-39-24.txt](https://github.com/Andersama/obs-asio/files/15412782/2024-05-23.08-39-24.txt)
[Crash 2024-05-23 08-39-48.txt](https://github.com/Andersama/obs-asio/files/15412785/Crash.2024-05-23.08-39-48.txt)

Was able to reproduce the crash in the same way by simulating a device disconnect, using version `v3.2.1f`. Unplugging is the only way of reliably reproducing this unfortunately
