### ISSUE TITLE
Issue with Focusrite Scarlett 2i2 buffer sizes

### ISSUE THREAD

**Issue by shuttyt** [Andersama/obs-asio#24]
I'm using Scarlett 2i2 1st gen on Win 7. All drivers and OBS (and plugin) versions current.

When setting up the ASIO device settings, the buffer size in the OBS drop-down only allows for buffer sizes at unusual increments (i.e. 200, 216, 232, 248, 264, etc.), whereas the Focusrite software only allows certain values, based off 16 (i.e. 96, 160, 192, 256, etc.).

Once I try to apply the closest setting, I'm getting 'IRQL NOT LESS OR EQUAL' BSOD's.

**Comment by pkviet** [comment]
imo it's a fucked up driver; i have the 2i2 second gen and i've never had that kind of issue.
Try downgrading the driver to check whether it makes any difference or not.
If the issue persists and if you're dev minded, you could try compiling the other version of the plugin (relying on bassasio library, check the wiki)

**Comment by pkviet** [comment]
Hi, please try with obs-asio v2.0.0 and report

**Comment by pkviet** [comment]
closing since there's not been any follow up; re-open if necessary
