### ISSUE TITLE
Roland Studio Capture not working with OBS and ASIO

### ISSUE THREAD

**Issue by ruleth** [Andersama/obs-asio#28]
OBS ASIO does detect the Roland Studio Capture, but under Obs Channel 1 and Channel 2, the only options are "Mute."

Whenever my DAW isn't using the Studio Capture, it shows all the various inputs.

Any help appreciated!

**Comment by pkviet** [comment]
The plugin is working correctly then.
It's a limitation of asio sdk: a device can't be used by several apps at
the same time. There are exceptions like rme devices.
If you want to use your daw and obs at the same time you'll have to route
audio with a virtual asio device.
Check the wiki for hints.
