### ISSUE TITLE
The ASIO tab doesn't appear in OBS (I can't record Kontakt 6)

### ISSUE THREAD

**Issue by martin540** [Andersama/obs-asio#30]
My OBS doesn't show the ASIO tab even though I was able to add a new "ASIO" input. I can't record anything from Kontakt 6, in the properties it says **OBS channels are not connected**. What should I do? I got the newest release and the newest OBS.

![Poznámka 2019-11-25 174326](https://user-images.githubusercontent.com/52452677/69560243-be045280-0fab-11ea-833b-6750ded1c84c.jpg)

**Comment by pkviet** [comment]
There's no asio entry on top any more if you're using v2. Only on earlier
versions.
What's your asio device ?
If you're trying to capture audio from a daw, it won't work. Don't know
what's Kontakt 6 but it doesn't seem to be a device ...

**Comment by pkviet** [comment]
closing since there's not been any follow-up. Feel free to re-open.
