### ISSUE TITLE
not working ZOOM H5 multi track asio driver

### ISSUE THREAD

**Issue by Aleksandr555** [Andersama/obs-asio#31]

**Comment by pkviet** [comment]
Could you elaborate ? without any log or more info, it's impossible to troubleshoot.
I'm pretty sure i've seen people with a zoom device working ...
You need to tell us which version of the plugin you tried, the obs version, plus a log at a minimum.
Without that I won't be able to help you.

**Comment by Aleksandr555** [comment]
Hello! I tried version 2.0.0 of the plugin. I've got...Zoom H5and I'm trying to feed three microphones in OBS.I can even do it sometimes and write it down, but... - 1 time and 10 tries. After restarting the program, the driver itself ASIO in OBS
I can see. but - none of the microphones are available - empty. Thank you so much for coming forward.

6 декабря 2019, 18:39:55, от "pkv" <notifications@github.com>:

Could you elaborate ? without any log or more info, it's impossible to troubleshoot.
I'm pretty sure i've seen people with a zoom device working ...
You need to tell us which version of the plugin you tried, the obs version, plus a log at a minimum.
Without that I won't be able to help you.

**Comment by pkviet** [comment]
it's probably because you're using the zoom driver in another app for instance a DAW (ableton, reaper, etc): ASIO is exclusive. Some manufacturers write asio drivers which bypass this defect (ex: RME) but most do not.

**Comment by Aleksandr555** [comment]
нет, не использовал - только OBS

6 декабря 2019, 19:10:55, от "pkv" <notifications@github.com>:

it's probably because you're using the zoom driver in another app for instance a DAW (ableton, reaper, etc): ASIO is exclusive. Some manufacturers write asio drivers which bypass this defect (ex: RME) but most do not.

**Comment by Aleksandr555** [comment]
No, I didn't, just...OBS

6 декабря 2019, 19:20:43, от "Александр" <current-choice@ukr.net>:

нет, не использовал - только OBS

6 декабря 2019, 19:10:55, от "pkv" <notifications@github.com>:

it's probably because you're using the zoom driver in another app for instance a DAW (ableton, reaper, etc): ASIO is exclusive. Some manufacturers write asio drivers which bypass this defect (ex: RME) but most do not.

**Comment by pkviet** [comment]
ok drop a log here then. Menu Help > Log Files > Show current log

**Comment by Aleksandr555** [comment]
https://obsproject.com/logs/C4CcgUeNDk3gh-qI

6 декабря 2019, 19:33:40, от "pkv" <notifications@github.com>:

ok drop a log here then. Menu Help > Log Files > Show current log

**Comment by pkviet** [comment]
obs-asio plugin is not installed in the log you've dropped

**Comment by pkviet** [comment]
closing since there's no movement. Feel free to reopen
