### ISSUE TITLE
Can't record sound

### ISSUE THREAD

**Issue by SAARussian** [Andersama/obs-asio#32]
Im using DAW with asio4all

**Comment by pkviet** [comment]
well, at least drop a log. Don't expect any help with so few info. I suspect though that you haven't checked the wiki. Read the section regarding capture of audio outputs.

**Comment by SAARussian** [comment]
![image](https://user-images.githubusercontent.com/57723354/70546989-3577db80-1b81-11ea-9b04-f91e674c04ee.png)

**Comment by pkviet** [comment]
that's not a log. In obs, go to Help menu > log > show current log

**Comment by SAARussian** [comment]
[2019-12-10 19-21-07.txt](https://github.com/Andersama/obs-asio/files/3945934/2019-12-10.19-21-07.txt)

**Comment by pkviet** [comment]
the plugin is loaded correctly by obs; can you create an asio source and make a screenshot of its Properties menu ? also drop the new log after having created the source

**Comment by SAARussian** [comment]
![image](https://user-images.githubusercontent.com/57723354/70548145-1f6b1a80-1b83-11ea-84c8-0bc77ff05127.png)
[2019-12-10 19-26-27.txt](https://github.com/Andersama/obs-asio/files/3945955/2019-12-10.19-26-27.txt)

**Comment by pkviet** [comment]
the log is fine and your screenshot too, except that you need to unmute and select an input channel

**Comment by SAARussian** [comment]
I need to record only output sound from sound card
![image](https://user-images.githubusercontent.com/57723354/70548745-247c9980-1b84-11ea-9c4e-30db5bca7dc9.png)

**Comment by pkviet** [comment]
it's not possible to capture asio outputs, the asio sdk does not allow it.
One can only capture inputs.
Some manufacturers write drivers which allow asio output capture (ex: RME) but they're an exception.
You need to read the wiki section on Capturing Outputs (I explain there a workaround using reaper and an asio vritual driver)

**Comment by SAARussian** [comment]
https://github.com/Andersama/obs-asio/wiki/Installation-and-Usage-(new-versions-2.0.0-or-later)
![image](https://user-images.githubusercontent.com/57723354/70549510-622df200-1b85-11ea-8304-346a3c82fe4e.png)

**Comment by SAARussian** [comment]
Without reaper there is no way?

**Comment by pkviet** [comment]
you need an asio virtual driver; you could try Voicemeeter . FL Studio also provides such a thing.

**Comment by SAARussian** [comment]
voicemeeter seems intresting, but I think asio4all have much problem...

**Comment by pkviet** [comment]
instead of using asio4all, if you really want to use asio you should try to use a real asio hadware sound card...
Closing now since your issue is that you want to capture outputs.

**Comment by SAARussian** [comment]
I use behringer u-phoria um2

**Comment by pkviet** [comment]
if you have issues with the um2 and asio open another issue. Should work fine though if it has asio drivers.

**Comment by SAARussian** [comment]
official supported only asio4all

**Comment by pkviet** [comment]
ah too bad, you're in bad luck then

**Comment by SAARussian** [comment]
OK, I'll keep looking for a way to record audio with asio
