### ISSUE TITLE
crashes when connecting to jackrouter asio plugin

### ISSUE THREAD

**Issue by darrenliew96** [Andersama/obs-asio#34]
obs immediately crashes when jackrouter asio plugin is selected in ASIO plugin OBS windows 10 64bit.

**Comment by pkviet** [comment]
jackrouter is not maintained on windows; I managed to got it to work a long while ago, but haven't tested with the latest release of the plugin.
If you know how to compile, you might want to try the bassasio versio nfo the plugin to see if it makes any difference
