### ISSUE TITLE
OBS isn't getting input, no ASIO settings options

### ISSUE THREAD

**Issue by domportera** [Andersama/obs-asio#35]
No matter what I do I can't get this to receive input from Reaper.

In Reaper I've tried setting my ASIO Driver to my Focusrite and ReaRoute. In OBS I've tried what little options are available to me.

Am I doing something wrong? How can I get this to work? Let me know if you need more information.

![image](https://user-images.githubusercontent.com/6530600/71335328-42e17e00-2510-11ea-94d1-ad9850ae7ed9.png)

**Comment by pkviet** [comment]
drop a screenshot of your reaper hardware routing, to see if you've set correctly the routing of your tracks / master track.
Did you try to follow the wiki instructions ? 
Your screenshot of obs is correct, so my bet is you're doing something wrong in Reaper.

**Comment by domportera** [comment]
I did try to follow the wiki instructions, and I followed them until it mentioned the ASIO config button, which doesnt exist on my UI. I hope im doing something wrong haha, if so sorry to bug you!

Here's my two settings I tried:
![image](https://user-images.githubusercontent.com/6530600/71385171-b12b4c80-25b3-11ea-80ef-c2cf4b5ed642.png)

![image](https://user-images.githubusercontent.com/6530600/71385181-be483b80-25b3-11ea-9bfe-1e24abb5951b.png)

**Comment by pkviet** [comment]
sorry, i had not noticed your answer ...
So if it still applies, the right setting is in the first screenshot. Focusrite does have a setup panel so I'm surprised by what you say. You access it either directly from windows or from Reaper: in the first screenshot, click on Asio Configuration.
Did you follow all steps in https://github.com/Andersama/obs-asio/wiki/Capturing-mixes ?
You need to create the hardware outputs

**Comment by domportera** [comment]
No worries, thank you for getting back to me. It's been a while and I don't remember what I tried, but this is still important to me so I will do my best asap. Rn I'm out of the country but I'll get back to you with my results - it's very possible I was doing something wrong

**Comment by domportera** [comment]
Ok so I got a chance to check it out despite being abroad, and it seems that did the trick! At least on this computer, though i'm certain it's no different when I get home.

Sorry I didn't see that article, I thought I looked everywhere but clearly that was a massive oversight on my part. Thanks so much for walking this dummy through it :)

Also useful tidbit for anyone trying to use Reaper Portable - you can still use ReaRoute if you install a separate full version of Reaper w/ the plugin, then copy and paste the rearoute dll from the full install's root folder into your portable install's root folder.
