### ISSUE TITLE
 Zoom H6 not working?

### ISSUE THREAD

**Issue by siverpro** [Andersama/obs-asio#37]
Hi, I'm having issues with my Zoom H6 not being able to select individual outputs. It's supposed to have one stereo input plus four mono channels. I'm not able to select them in OBS.

![Screenshot from 2020-01-16 16-07-51](https://user-images.githubusercontent.com/27547222/72536433-85ca1380-387a-11ea-9e2a-d8864fc77e93.png)

**Comment by pkviet** [comment]
the most likely explanation is because you're using the device with another asio application. Asio is exclusive, an asio device usually can't be shared between several apps.

**Comment by siverpro** [comment]
Which applications? I have no other ASIO applications as far as I know. It's a fresh install of Windows, OBS 24 and this plugin along with the H6 driver are the only things installed on this computer.

**Comment by pkviet** [comment]
no daw is open ? very odd. Drop a log of obs then

**Comment by siverpro** [comment]
I disconnected the H6, rebooted and re-connected it and now I get this:
![Screenshot from 2020-01-16 17-42-05](https://user-images.githubusercontent.com/27547222/72544434-a2b91380-3887-11ea-9d93-65b39255ebe2.png)

Thanks for the support!

**Comment by pkviet** [comment]
cool, closing then

**Comment by siverpro** [comment]
You can add Zoom H6 to the supported/tested devices then =)
