### ISSUE TITLE
Obs-asio not showing asio options

### ISSUE THREAD

**Issue by arunki** [Andersama/obs-asio#39]
Hi, guys

@Andersama

I fresh installed OBS 24.0.3 64 on Win 10 and also the obs-asio-installer_2.0.0_obs24.
The menu bar of OBS does not show the ASIO option.

Someone gives a hand?

Thanks a lot

**Comment by pkviet** [comment]
There's no Asio entry in the top Menu anymore since obs-asio 2.0.0.

**Comment by arunki** [comment]
How to make the settings, please??

**Comment by pkviet** [comment]
you open the Control Panel of your device and set your device there. But this is external to obs. So it's less work for you actually if you've already setup your asio device (sample rate and buffer size)
