### ISSUE TITLE
ASIO tab does not show up

### ISSUE THREAD

**Issue by krijul** [Andersama/obs-asio#41]
I am currently using a focusrite 2in2 interface and after i install the asio plugin successfully, nothing shows up when i restart obs studio
i realize now that their isnt a tab for asio anymore however even still using audio output capture or asio in the sources tab, i can not get audio when using focusrite usb asio
https://obsproject.com/logs/oFIXcYtDbvH7UQXj

**Comment by pkviet** [comment]
i've been using the same focusrite without issues.
What's your setup ? do you a mike hooked up to input 1 on the front for instance ? 
are you using your focusrite in obs AND a daw at the same time ?
If you do, it's why it doesn't work.
Asio is exclusive: it wants only a single app loading the asio device drivers....
(there are exceptions though, depending on how smartly the manufacturers wrote their drivers)

**Comment by krijul** [comment]
okay i see yea i have a daw open that makes sense. thank you for the quick response super helpful!
