### ISSUE TITLE
asio tab is not displayed

### ISSUE THREAD

**Issue by DirkLazybones** [Andersama/obs-asio#42]
Hi,
I installed OBS 24.0.3. Then Iinstalled obs-asio. The obs-asio.dll and the asio.pdb file are in the plugin folder but in OBS the ASIO tab is not shown.
Did I something wrong?

**Comment by pkviet** [comment]
There is no asio tab any more since version 2.0.0 : it's not needed anymore. Read the wiki:
https://github.com/Andersama/obs-asio/wiki/Installation-and-Usage-(new-versions-2.0.0-or-later)

There are separate instructions for pre and post v2
