### ISSUE TITLE
Stopped working in OBS

### ISSUE THREAD

**Issue by paulknakk** [Andersama/obs-asio#46]
https://www.twitch.tv/videos/581894325 at 1:26:00 everything was working fine and then the mic cut out.  The interface was still receiving audio (I could still monitor myself) but OBS was receiving nothing.  Shutting down the stream and restarting OBS fixed the issue.  Not sure what would have caused it.

**Comment by pkviet** [comment]
This can happen if there are buffering issues. Check in obs log whether there's a max buffer entry and whether your device is the culprit.
If it is the case, increase the buffer of your device in its asio settings panel.
