### ISSUE TITLE
After installing Asio plugin for OBS, OBS doesn't load.

### ISSUE THREAD

**Issue by Rooster128** [Andersama/obs-asio#47]
Hey there! Having trouble with the ASIO OBS plugin. It seems like upon installing it, when trying to load OBS 24.0.3 (64 bit), it fails to load.
I see OBS sitting in the Process Explorer for a minute or so upon loading, looks like it tries to do something with memory, then it disappears.
The second I remove the plugin, I am able to load OBS normally. I tried restarting computer after installing and trying to start OBS then, it made no difference. Tried running as Admin as well.

Currently trying to get a Pioneer XDJ-R1 to load up on OBS.

**Comment by pkviet** [comment]
Which version of the plugin are you using?

**Comment by Rooster128** [comment]
First one I saw on the page I was linked to, 2.0.2, could that be the issue?

**Comment by pkviet** [comment]
Mmh. That's the latest version.
I compiled it today, but haven't tested widely. Let me confirm it works for
other people.
I'll get back to you

**Comment by ConsultBuckner** [comment]
Same issue here... Windows 7 64-bit, OBS 24.0.3.0

**Comment by pkviet** [comment]
Check the notes for 2.0.2 ; it's for obs v25 or later.
For obs 24.0.3 use v2.0

**Comment by Rooster128** [comment]
Surprised I didn't see that myself. Updated my OBS and it fixed the problem- thank you.
