### ISSUE TITLE
asio stops working after several minutes

### ISSUE THREAD

**Issue by JasonNPitt** [Andersama/obs-asio#49]
Hey Guys

This plugin works great, for about 5 minutes, then it stops working, the audio signal is still coming into the interface, but OBS isn't seeing it...I have to reselect the device from the osb properties dialog and then it starts working again...help

**Comment by pkviet** [comment]
hi
i'll need more info. CAn you drop obs log ? what's the device ?
Try to set a higher buffer in the control panel of your device.

**Comment by JasonNPitt** [comment]
It's a lexicon fw810s. I've tried increasing the buffer size as high as it
will go, 3000 something, and it still happens. I'll run it again in a
second and get a log for you.

**Comment by JasonNPitt** [comment]
[fw810s.txt](https://github.com/Andersama/obs-asio/files/4447064/fw810s.txt)

see log file.  I worked fine for about 25 minutes this time before dying.  After it died the interface was still monitoring audio but OBS wasn't detecting it.  Went to the OBS asio properties panel and switched from stereo to 2.1 and it started working again.

**Comment by pkviet** [comment]
It's very likely unrelated to asio.
Your usb2 webcam is reaching max buffer.
This will remove audio from output.
Check this by removing the webcam.
It buffers because its bandwidth is too small. Try another port,
preferrably not on same hub and preferrably usb3.
