### ISSUE TITLE
Audient ID4: No audio

### ISSUE THREAD

**Issue by quantumleap33** [Andersama/obs-asio#50]
I have an Audient ID4 and the ASIO source doesn't seem to be working. I am trying to stream Ableton Live sound into OBS so I insert an ASIO source, select the Audient ASIO driver, set OBS Channel 1 and 2 to the corresponding Analogue 1 and 2, click OK but metering is not reacting. I tried running both apps as admin but no luck. I am including the log:

04:23:51.368: CoInitializeEx succeeded: 0x00000001
04:23:51.368: CPU Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
04:23:51.368: CPU Speed: 2208MHz
04:23:51.368: Physical Cores: 6, Logical Cores: 12
04:23:51.368: Physical Memory: 16178MB Total, 10267MB Free
04:23:51.368: Windows Version: 10.0 Build 18363 (release: 1909; revision: 752; 64-bit)
04:23:51.368: Running as administrator: true
04:23:51.368: Aero is Enabled (Aero is always on for windows 8 and above)
04:23:51.368: Windows 10 Gaming Features:
04:23:51.368: 	Game Bar: On
04:23:51.368: 	Game DVR: On
04:23:51.368: 	Game DVR Background Recording: Off
04:23:51.369: Sec. Software Status:
04:23:51.371: 	Windows Defender Antivirus: enabled (AV)
04:23:51.371: Current Date/Time: 2020-04-09, 04:23:51
04:23:51.371: Browser Hardware Acceleration: true
04:23:51.371: Portable mode: false
04:23:51.732: OBS 25.0.4 (64-bit, windows)
04:23:51.732: ---------------------------------
04:23:51.751: ---------------------------------
04:23:51.751: audio settings reset:
04:23:51.751: 	samples per sec: 44100
04:23:51.751: 	speakers:        2
04:23:51.751: ---------------------------------
04:23:51.751: Initializing D3D11...
04:23:51.751: Available Video Adapters: 
04:23:51.756: 	Adapter 0: NVIDIA GeForce GTX 1060 with Max-Q Design
04:23:51.756: 	  Dedicated VRAM: 2051014656
04:23:51.756: 	  Shared VRAM:    4187109376
04:23:51.756: 	  PCI ID:         10de:1c20
04:23:51.757: 	  Driver Version: 26.21.14.4219
04:23:51.757: 	  output 0: pos={0, 0}, size={3840, 2160}, attached=true, refresh=60, name=
04:23:51.757: 	  output 1: pos={1917, -1203}, size={1920, 1200}, attached=true, refresh=59, name=DELL 2405FPW
04:23:51.757: 	  output 2: pos={-3, -1200}, size={1920, 1200}, attached=true, refresh=59, name=BenQ 241W
04:23:51.757: 	Adapter 1: Intel(R) UHD Graphics 630
04:23:51.757: 	  Dedicated VRAM: 134217728
04:23:51.757: 	  Shared VRAM:    4187109376
04:23:51.757: 	  PCI ID:         8086:3e9b
04:23:51.757: 	  Driver Version: 26.20.100.7262
04:23:51.762: Loading up D3D11 on adapter NVIDIA GeForce GTX 1060 with Max-Q Design (0)
04:23:51.816: D3D11 loaded successfully, feature level used: b000
04:23:51.816: DXGI increase maximum frame latency success
04:23:51.816: D3D11 GPU priority setup success
04:23:52.558: ---------------------------------
04:23:52.558: video settings reset:
04:23:52.558: 	base resolution:   1920x1200
04:23:52.558: 	output resolution: 1920x1200
04:23:52.558: 	downscale filter:  Bicubic
04:23:52.558: 	fps:               60/1
04:23:52.558: 	format:            NV12
04:23:52.558: 	YUV mode:          601/Partial
04:23:52.558: NV12 texture support enabled
04:23:52.560: Audio monitoring device:
04:23:52.560: 	name: Default
04:23:52.560: 	id: default
04:23:52.560: ---------------------------------
04:23:52.569: [CoreAudio encoder]: Adding CoreAudio AAC encoder
04:23:52.570: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
04:23:52.622: [AMF] Unable to load 'amfrt64.dll', error code 126.
04:23:52.624: [AMF] AMF Test failed due to one or more errors.
04:23:52.624: Failed to initialize module 'enc-amf.dll'
04:23:52.651: [obs-browser]: Version 2.8.6
04:23:52.655: NVENC supported
04:23:52.679: VLC found, VLC video source enabled
04:23:52.743: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
04:23:52.744: No blackmagic support
04:23:52.750: ---------------------------------
04:23:52.750:   Loaded Modules:
04:23:52.750:     win-wasapi.dll
04:23:52.750:     win-mf.dll
04:23:52.750:     win-dshow.dll
04:23:52.750:     win-decklink.dll
04:23:52.750:     win-capture.dll
04:23:52.750:     win-asio.dll
04:23:52.750:     vlc-video.dll
04:23:52.750:     text-freetype2.dll
04:23:52.750:     rtmp-services.dll
04:23:52.750:     obs-x264.dll
04:23:52.750:     obs-vst.dll
04:23:52.750:     obs-transitions.dll
04:23:52.750:     obs-text.dll
04:23:52.750:     obs-qsv11.dll
04:23:52.750:     obs-outputs.dll
04:23:52.750:     obs-filters.dll
04:23:52.750:     obs-ffmpeg.dll
04:23:52.750:     obs-browser.dll
04:23:52.750:     image-source.dll
04:23:52.750:     frontend-tools.dll
04:23:52.750:     enc-amf.dll
04:23:52.750:     decklink-ouput-ui.dll
04:23:52.750:     coreaudio-encoder.dll
04:23:52.750: ---------------------------------
04:23:52.750: ==== Startup complete ===============================================
04:23:52.765: All scene data cleared
04:23:52.765: ------------------------------------------------
04:23:52.844: WASAPI: Device 'Speakers (Audient iD4)' [44100 Hz] initialized
04:23:52.901: WASAPI: Device 'Line (Audient iD4)' [44100 Hz] initialized
04:23:52.922: WASAPI: Device 'Line (Audient iD4)' [44100 Hz] initialized
04:23:52.943: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)
04:23:52.943: 
04:23:53.007: asio-input: Starting (Audient USB Audio ASIO Driver)
04:23:53.007: Switched to scene 'Scene'
04:23:53.007: ------------------------------------------------
04:23:53.007: Loaded scenes:
04:23:53.007: - scene 'Scene':
04:23:53.008:     - source: 'ASIO' (asio_input_capture)
04:23:53.008: ------------------------------------------------
04:23:53.261: [ffmpeg] [AVIOContext @ 0000020a9e8bea80] Statistics: 386 bytes read, 0 seeks
04:24:06.132: adding 23 milliseconds of audio buffering, total audio buffering is now 69 milliseconds (source: ASIO)
04:24:06.132:

**Comment by pkviet** [comment]
You haven't read the wiki.
You have some basic misunderstandings.
Why do you expect an input capture plugin to be able to capture outputs of
your device ?
Secondly, asio sdk does not allow capture of outputs anyway.
Thirdly, asio is exclusive: its sdk prevents the concurrent use of an asio
device in several apps. Some drivers are able to work around that
limitation but most don't.

**Comment by quantumleap33** [comment]
Ok, I see. The DAWs output goes to the soundcard anyway. Desktop audio tracks whatever is played on the soundcard. Shouldn't have OBS captured that?

**Comment by pkviet** [comment]
desktop audio uses wasapi (windows audio api) not asio. In general the manufacturers of asio device don't give the sama capabilities to the wasapi driver as the asio driver: latencies for instance are lower in asio. So more oftne than not the wasapi drivers are crippled.

**Comment by quantumleap33** [comment]
Ok, thanks. Tried ASIO4ALL, worked for a bit then crashed the DAW. What a mess, cannot believe there is no stable solution. I will have a look around.

**Comment by pkviet** [comment]
Avoid asio4all.
Read the wiki section on Capturing outputs for a workaround.
It'll work with Reaper or FL Studio . Not Ableton though.a

**Comment by quantumleap33** [comment]
Yeah, I read it. I use Ableton and I want to make a live stream with Ableton audio. So many people do it. Weird. Can I ask, what's the point of this obs ASIO driver, then?

**Comment by quantumleap33** [comment]
Ok, sorry, I guess, it's for inputs...

**Comment by quantumleap33** [comment]
Ok, it works using MME/DirectX driver type, so I guess, I will be using that.
