### ISSUE TITLE
Loading VSTs to ASIO Source crashes OBS 

### ISSUE THREAD

**Issue by RavenStreamer** [Andersama/obs-asio#52]
As the title says, when I add a VST plugin to an ASIO audio source in OBS the program crashes. I'm using OBS 25.0.4 and ASIO plugin 2.0.2,

**Comment by pkviet** [comment]
It would be helpful to follow the bug template and post an obs log and a crash log.
Also tell exactly what is the device and the vst. Have you tried several vst ? All crash ?
What's the obs version ?
As it stands, your report is too terse, that's an understatement ...

**Comment by RavenStreamer** [comment]
Sorry - new at this. 

My laptop is an HP Pavilion 17, AMD A10-5754M, APU with Radeon HD Graphics 2.10 GHz, 12GB RAM. As already listed, I'm using OBS 25.0.4. ASIO plugin 2.0.2. Crashes with any VST plugin. 
Log & Crash reports:
https://obsproject.com/logs/liu0nnoh7QO4P-xz
https://obsproject.com/logs/AkeI2JCu7tm81yBl

**Comment by RavenStreamer** [comment]
I have also tried downgrading to OBS 25.0.1 but still encounter the problem. 
The built-in audio filters in OBS work fine with the plugin.

**Comment by RavenStreamer** [comment]
A complete uninstall/reinstall of OBS 25.0.4 and ASIO 2.0.2 seems to have done it. Can now add VST's to my ASIO input.

**Comment by pkviet** [comment]
does it crash as soon as yo utry to add a vst ? are you able to select a vst at all ? did you check if with a NON asio source VST filters work ?
Your crash log does not show an issue with the asio plugin ...
On my side, I can load a vst without issues:
![obs64_Qt88MCOYXd](https://user-images.githubusercontent.com/9283407/79774891-b87d1f80-8333-11ea-8491-10fee97de836.png)

**Comment by pkviet** [comment]
Ok solved by Fenrir on discord , thanks to him. Closing
