### ISSUE TITLE
32 bit build

### ISSUE THREAD

**Issue by olegchir** [Andersama/obs-asio#53]
Is it hard to build 32-bit libs?
If it's an easy one-click action, could you please do it?

**Comment by pkviet** [comment]
nope it's not a one click action because you need to link to 32 bit libobs. So we won't release any 32 bit version, sorry.

**Comment by foxx1337** [comment]
Hoping to bump this up. In my use case I run Rocksmith 2014 Remastered (x86) with rs_asio (x86) and Reaper x86 (for Rocksmith compatibility). I connect the game to ReaRoute and want to consume ASIO audio in OBS x86 with obs-asio x86.

I'll try to build it myself and report, but an official release is a much more reputable resource.
