### ISSUE TITLE
No asio tab in OBS

### ISSUE THREAD

**Issue by MokkaGuy** [Andersama/obs-asio#56]
Hi! I have OBS ver.25.0.8 ..and obs-asio ver. 2.0.2.b.    (Windows 10 x64)
But there is no ASIO tab in obs after installing. I don't know why. Made a full reinstall and still no.

**Comment by pkviet** [comment]
You haven't **checked the wiki** it seems. There's no tab. No asio menu either. In the sources dock, when adding a new source, you'll have a new entry : ASIO.
