### ISSUE TITLE
Inputs disappear in "Studio Mode"

### ISSUE THREAD

**Issue by eaaronhorsham** [Andersama/obs-asio#57]
First this plugin has been a great replacement for the built in audio in OBS Studio. 

However the ASIO inputs do not show up in the OBS mixer when in studio mode. The inputs showed up when I first installed the plugin and added the sources, then mysteriously disappeared and are listed as "Inactive" in the advanced audio properties of OBS. 

If I exit studio mode then the inputs are in the OBS mixer showing as normal. The audio is passing to the stream and recording even when the meters and controls aren't showing, but you cannot monitor levels. It also retains level and mute state, so if the input was muted on the non-studio view it stays muted but you can't see that it is muted. This is problematic when I live in Studio Mode 99.9% of the time.

Single Mode Mixer:
![Single_Mode](https://user-images.githubusercontent.com/65149221/83948025-a45c8700-a7e8-11ea-831d-720ba3cede65.JPG)
Studio Mode Mixer:
![Studio-Mode](https://user-images.githubusercontent.com/65149221/83948029-a45c8700-a7e8-11ea-8a6a-4a6bae3e2186.JPG)
Single Mode Advanced Audio Properties:
![Single_Mode_AAP](https://user-images.githubusercontent.com/65149221/83948027-a45c8700-a7e8-11ea-8637-abe342124d86.JPG)
Studio-Mode Advanced Audio Properties:
![Studio_Mode_AAP](https://user-images.githubusercontent.com/65149221/83948028-a45c8700-a7e8-11ea-9585-ef87e780453a.JPG)

**Comment by pkviet** [comment]
NOT a bug.
It's how studio mode works.
What's displayed in Sources is what's in the scene selected for  Preview.
While in the Mixer, it's what is in the scene active for Program.

**Comment by eaaronhorsham** [comment]
Sorry meant to add. This is happening on 2 different PCs running fresh installs of OBS Studio 25.0.8. It was also happening in 25.0.1 prior.

**Comment by pkviet** [comment]
uh maybe my answer crossed your last comment ?

**Comment by eaaronhorsham** [comment]
No sorry, I understand the audio source only when in program as otherwise you would have a mess, but the source is not showing in the mixer when in Program

**Comment by eaaronhorsham** [comment]
Those screen captures are with the scene in Program.

**Comment by pkviet** [comment]
did you transition to the new scene, really ?
I definitely can't repro.

**Comment by pkviet** [comment]
screenshot your whole obs window

**Comment by eaaronhorsham** [comment]
Yes. I have run 6 live streams using ASIO source in the past week. I live in studio mode, all my sources have the same ASIO input feeding from house mixer. never shows up. Will get the screen capture in one minute.

**Comment by eaaronhorsham** [comment]
Loaded same scene into Program and Preview Both studio and sing modes shown.

![Studio_Full](https://user-images.githubusercontent.com/65149221/83948511-9eb47080-a7eb-11ea-8574-ce90b4bc6913.JPG)
![Single_Full](https://user-images.githubusercontent.com/65149221/83948515-a247f780-a7eb-11ea-8668-46c69cba1040.JPG)

**Comment by eaaronhorsham** [comment]
There are a couple others having the same issue that posted in the OBS Studio Forum.

**Comment by pkviet** [comment]
have a link ? definitely can't repro

**Comment by eaaronhorsham** [comment]
OBS-Forum:
https://obsproject.com/forum/threads/audio-source-goes-inactive-when-engaging-studio-view.119692/

For reference I have the same issue on this PC Windows 10 and the windows 10 PC I just built for our church streams.

**Comment by eaaronhorsham** [comment]
It also doesn't report mute status back to my Streamdeck when in studio mode, but does in single.

**Comment by pkviet** [comment]
i need clear repro steps.
do you use the asio source in several scenes ?
if yes, did you paste by reference or duplicate ?

**Comment by pkviet** [comment]
i suspect it's related to either groups or scenes because the plugin does nothing related with studio mode. It's completely  controlled by obs UI.

**Comment by eaaronhorsham** [comment]
ASIO source is Focusrite Scarletts in both locations.
Source is in multiple scenes(all but 2 in our church rig as it is our main input) using "Existing Source" so settings track between scenes.
I have tried creating a new Profile and scene collecion with 2 scenes, one with ASIO one without. and have the same results.

**Comment by pkviet** [comment]
yes but did you paste by reference or duplicate ? you have two choices when adding the same source to several scenes

**Comment by eaaronhorsham** [comment]
Just tried one scene only source is the ASIO input, same result.

I select Add->ASIO->Add Existing then select the source that is populated. So that should be a reference not duplicate.

**Comment by pkviet** [comment]
That's probably an obs bug and not an obs-asio one. I'll check anyway.

**Comment by pkviet** [comment]
you don't have groups or nested scenes ?

**Comment by eaaronhorsham** [comment]
I have groups in the church rig not home, but they only contain PNG graphics, the ASIO sources are kept at the bottom out of any groups.

It doesn't do it with NDI audio or direct audio input capture sources just the ASIO.

**Comment by eaaronhorsham** [comment]
Additional plugins I have are common to both machines
NewTek NDI
Websocket
Elgato Stream Deck

Differences
ReStream at church
Virtual Cam at home

**Comment by pkviet** [comment]
Can you post a log ?

**Comment by eaaronhorsham** [comment]
I ran through a loop of scenes 3 with and 2 without ASIO input. First in Studio then in Single.

[ASIO_viewissue_2020-06-06 12-24-19.txt](https://github.com/Andersama/obs-asio/files/4740603/ASIO_viewissue_2020-06-06.12-24-19.txt)

**Comment by pkviet** [comment]
try the last binary ; you're not using the last one.
First uninstall the previous binary, and install the latest.
The libobs lib  was changed in between so sources are a bit different.

**Comment by eaaronhorsham** [comment]
Latest binary for OBS or OBS-ASIO?
Is the 2.0.2b installer not compiled with the last binary?

**Comment by pkviet** [comment]
yes it's the last release. But  your log shows the old dll (named obs-asio.dll) while the curent one is win-asio.dll.
So try: uninstalling, manually inspect the obs-pluing subfolder (if obs-asio.dll is there, remove it), reinstall.
Check that you have only win-asio.dll.
And in your log, win-asio.dll should be listed.

**Comment by eaaronhorsham** [comment]
So I uninstalled, checked the plugin folder and there was not obs-asio.dll.
Reinstalled, now there is a WIN-ASIO.dll, but behavior is still incorrect with the same issue in OBS Studio.
New Log.

[With_WIN-ASIO_2020-06-07 14-33-21.txt](https://github.com/Andersama/obs-asio/files/4742689/With_WIN-ASIO_2020-06-07.14-33-21.txt)

**Comment by pkviet** [comment]
Mmh. Could you post your scene json ?
(The folder can be reached through the File menu).
I want to check the flags. I wonder if there's a corruption which has
persisted.
(A check also would be to remove the asio source and readd)

Also, in the forum link, the repro steps seem to differ from yours.

**Comment by eaaronhorsham** [comment]
Here is the json scene file
I did try removing all ASIO sources and re-added. Still same behavior.

The forum link has the same issue as far as I can tell. Enabling studio mode marks the ASIO as inactive and hides from mixer, but still passes audio to stream and record.

[Untitled.zip](https://github.com/Andersama/obs-asio/files/4743815/Untitled.zip)

**Comment by eaaronhorsham** [comment]
Oh that JSON the ASIO is labeled "Test FRAS" and only in one scene "Clean Feed"

**Comment by eaaronhorsham** [comment]
OK So reading through the JSON I just figured out the common denominator.
In the transition settings menu if you enable "Duplicate Scene" and "Duplicate Sources" The ASIO device disappears from the Audio Mixer. If "Duplicate Scene" is selected but NOT "Duplicate Sources" The input shows in the mixer as expected when scene is in program.
![image](https://user-images.githubusercontent.com/65149221/83993476-87779f00-a921-11ea-93cc-e33844e18526.png)

This does not happen with an Audio Input Capture or audio sources attached to Decklink, NDI or Webcams.

I know that OBS doesn't apply the duplicate sources to those audio devices as only active sources in program show in the mixer, I'm guessing there is a flag, or variable in the obs-asio that is set differently than the other audio source dll. 

For now I can disable "Duplicate Sources" as I only need that function once in a while, but if there is a future fix that would be awesome. I know that it will bite me in the A** at some point.

Let me know if you want/need any other setup info from me. I would dive into the code to see if I could find it, but I don't have the time currently to get the rust off those skills.

**Comment by pkviet** [comment]
ok that's interesting. I can repro that. Very odd, the asio plugin has been there for a long time, so it's very odd.

**Comment by pkviet** [comment]
Fixed it; will post a binary later today.

**Comment by pkviet** [comment]
check the Releases section ; there a binary 2.0.2c. It fixes the issue.

**Comment by eaaronhorsham** [comment]
Awsome, Works like a charm, and won't bite my own A** thinking the input is open but actually sending dead air. Thank you.
