### ISSUE TITLE
Linux Install?

### ISSUE THREAD

**Issue by goldphnx** [Andersama/obs-asio#61]
It would be great if there could be a linux version/port of this plugin.

**Comment by Andersama** [comment]
In so far as I'm aware asio drivers are windows only. Pretty sure on linux the devices are usually available under something else, I don't develop for linux and the base code for windows is stable so I won't be working on a port.

The Juce api does have jack audio bindings, so presumably you could rebuild and enable those and it might work? Jack's already natively supported in obs anyway so I'd assume you'd be able to use your asio device in a low latency way.
