### ISSUE TITLE
ASIO source option missing in OBS 26.0.2

### ISSUE THREAD

**Issue by nathanielgranor** [Andersama/obs-asio#62]
Windows 10 64 bit machine
1. Installed latest OBS (26.0.2)
2. Installed latest obs-asio (2.0.3)
3. Verified win-asio.dll is in proper folder
4. Open OBS and try to add ASIO source

Result: it isn't in the list.

Let me know what additional info from my environment would be helpful to repro this

**Comment by nathanielgranor** [comment]
Since I suspected this was environmental, I tried the same steps on a different Windows machine and I did not run into the problem.

The computer with the issue is a Lenovo Thinkpad E495 running Windows 10 version 1909.
The computer where everything is working is running Windows 10 version 1903.

**Comment by nathanielgranor** [comment]
I found this entry in the OBS logs:

10:43:55.847: LoadLibrary failed for '../../obs-plugins/64bit/win-asio.dll': The specified module could not be found.
10:43:55.847:  (126)
10:43:55.847: Module '../../obs-plugins/64bit/win-asio.dll' not loaded

This suggests I'm missing a prerequisite library, perhaps one of the Windows C++ redistributables? Is there a version you require (2015, 2019, etc.)?

**Comment by nathanielgranor** [comment]
Aha!
I downloaded the latest C++ Redistributable (2019) and now the plugin is working. Perhaps add this to the FAQ?

**Comment by pkviet** [comment]
hello, yes indeed it's probably a redist which is missing: try the last redistributable
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
ha  i see your new message.
Great good call.
You can add it in the wiki if you want; anybody can edit. I'll add a word in the Releases

**Comment by nathanielgranor** [comment]
Wonderful, thanks for the awesome plug-in!
