### ISSUE TITLE
OBS Plugin

### ISSUE THREAD

**Issue by kotexe** [Andersama/obs-asio#64]
Hey. My name is Artyom, I am a marketer from Russia. Found your contacts on github. I'm looking for a person who will write a plugin for obs that will not send sound to broadcast from a specific source. If you can help, I'll tell you more. We will agree on the price.

**Comment by Andersama** [comment]
Just mute the source? If you need to monitor (listen to audio yourself, but not send out), monitoring the audio can be sent to a different device to avoid feedback.

I don't write plugins anymore, @pkviet may be a better one to ask.

**Comment by kotexe** [comment]
Thank you very much for your reply
