### ISSUE TITLE
ASIO tab isn't appearing in OBS 26.0.2

### ISSUE THREAD

**Issue by fredcrisp** [Andersama/obs-asio#67]
Self-explanatory. I've installed C++ and the .exe for OBS 26 yet the tab does not appear.

**Comment by pkviet** [comment]
Please read the usage entry in the wiki before posting issues. Which you should have done if you had followed the issue template. There's no tab any more ! :(

**Comment by fredcrisp** [comment]
god damn my laziness! thank you so much!

**Comment by fredcrisp** [comment]
it would be easier if ALL the videos online weren't referring to this tab.

**Comment by pkviet** [comment]
Old vids
