### ISSUE TITLE
OBS error log

### ISSUE THREAD

**Issue by vinnie2k** [Andersama/obs-asio#68]
Hi,

Here's my OBS error log:

21:39:24.834: asio-input: [win-asio: asio enabled]
21:39:24.834: asio-input: bassasio.dll loaded.]
...
21:39:38.402: asio-input: The driver could not be initialized

Is this on your side? I don't have any selection option in OBS:

![Capture d’écran 2020-11-04 213554](https://user-images.githubusercontent.com/9992145/98165908-f401c480-1ee6-11eb-9d13-9f3d2c6402f6.png)

Thank you for pointing me in the right direction.

**Comment by Jeffray00** [comment]
Hey,

got the same Problem here with v3. v2 works just fine, but recently tried to update to v3 and cant select/find my Device anymore (Rane MP2015):

If i look at Regedit i can find the ASIO Entry:
![image](https://user-images.githubusercontent.com/74115688/98450431-ff4e2d80-213c-11eb-99d6-27006344939e.png)

Heres a picture of the v3 menu:
![image](https://user-images.githubusercontent.com/74115688/98450440-1a20a200-213d-11eb-90c4-bc55886380c2.png)

And heres another with v2, works fine:
![image](https://user-images.githubusercontent.com/74115688/98450448-23117380-213d-11eb-87f0-f5e12e887608.png)


Thanks in advance :)

**Comment by pkviet** [comment]
@Jeffray00 use v2 then. If it works for you, no need to use v3. The capabilities are the same, but usually v3 with bassasio lib has better compatibility, though obviously not with your device.
@vinnie2k is your yamaha device used by a daw for instance ? Most asio devices have drivers with exclusive use: it's a limitation of asio sdk. A few driver manufacturers workaround that limitation.

**Comment by Jeffray00** [comment]
Alright, thanks for the Answer!

**Comment by vinnie2k** [comment]
@pkviet Sorry, forgot to update you: I updated Reaper and I now get the appropriate entries in the menu. I am not sure why but I think reinstalling it might re-registrered dlls or something.

Thank you for taking the time to respond to my request.

**Comment by pkviet** [comment]
Closing
