### ISSUE TITLE
Can't be used with "Generic Low Latency ASIO Driver" by Steinberg

### ISSUE THREAD

**Issue by shirok1** [Andersama/obs-asio#69]
Crashes when Device set to this.
[Crash 2020-11-22 11-48-46.txt](https://github.com/Andersama/obs-asio/files/5578881/Crash.2020-11-22.11-48-46.txt)
PS ASIO4ALL can't be used too. obs-audio will create an new instance of ASIO4ALL
![image](https://user-images.githubusercontent.com/12044683/99893342-c58f3200-2cb9-11eb-8385-d57735d2b170.png)

**Comment by Andersama** [comment]
Logs read like you're using the old port audio version, I can guarantee my friend @pkviet here hasn't built that for v26. You may want to visit the releases page.

That or double check you don't have two installs of the plugin, it's going to pick whatever first one it encounters in the folder.
