### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by styler2go** [Andersama/obs-asio#70]
When i am adding my device to OBS using this plugin i have no output.

Is there anything i can debug or try to get it working?

![Settings](https://i.imgur.com/D2xw5uR.png)

Setup:
Audient iD 14
Windows 10 64bit
OBS Studio 26.0.2

**Comment by pkviet** [comment]
post a log

**Comment by styler2go** [comment]
Here you go:

https://obsproject.com/logs/_E5eQIR2KjHpxJpC

**Comment by pkviet** [comment]
mmh asio-input: ASIO init: Unknown error when trying to start the device
My bet would be that you're using the device with another app at the same time, for instance a DAW. (check the wiki > troubleshooting section; have you done that ? There's a  template for posting issues for a reason btw.)

**Comment by styler2go** [comment]
Yes, i checked the Troubleshooting-Page.

To be honest, i had no issues-template when i created the issue, see here:

![](https://i.imgur.com/vESMALk.png)

I will check any running app but i am pretty sure that none is using asio.

**Comment by pkviet** [comment]
oh sorry, wtf, the template vanished.
I have no clue as to why your device can't init if it's not used at the same by another app. That's the most common source of errors.
I'd suggest to try v2 of the plugin.

**Comment by styler2go** [comment]
It instantly worked with v2. Should i just stay on that version? If so, i think we can close the issue. 

And thank you for your quick help!

**Comment by pkviet** [comment]
if it works with v2, yeah we will close.
