### ISSUE TITLE
Won't work with Behrenger umc 404hd in OBS

### ISSUE THREAD

**Issue by nuthinfancy** [Andersama/obs-asio#71]
Everything installed right. Go into ASIO control panel and see "ASIO not active"

**Comment by MatterialTrash** [comment]
I have spent hours trying to get this to work. Copied .dll file into correct directory. Reloaded Latest Version OBS Studio no option to add ASIO Capture Device. Trying to connect Denon MC3000 DJ controller through Behringer U-Control acu222 DAC Inputs. Please help.

**Comment by pkviet** [comment]
try version 2 of the plugin if it doesn't work with v3

**Comment by MatterialTrash** [comment]
> try version 2 of the plugin if it doesn't work with v3

Tried both No Dice.

**Comment by nuthinfancy** [comment]
> Everything installed right. Go into ASIO control panel and see "ASIO not active"

Found updated driver for umv404hd and it worked---but then it didn't. Just drops out for no apparent reason.

**Comment by pkviet** [comment]
i don't own that interface; without a log i can't troubleshoot anything ... A log is the minimum when help is requested !

**Comment by nuthinfancy** [comment]
Thee are logs from that night.
[2020-11-28 19-39-32.txt](https://github.com/Andersama/obs-asio/files/5629600/2020-11-28.19-39-32.txt)
[2020-11-28 14-19-54.txt](https://github.com/Andersama/obs-asio/files/5629601/2020-11-28.14-19-54.txt)
[2020-11-28 18-42-40.txt](https://github.com/Andersama/obs-asio/files/5629602/2020-11-28.18-42-40.txt)
[2020-11-28 18-43-13.txt](https://github.com/Andersama/obs-asio/files/5629603/2020-11-28.18-43-13.txt)

**Comment by MatterialTrash** [comment]
[2020-12-02 13-43-32.txt](https://github.com/Andersama/obs-asio/files/5629667/2020-12-02.13-43-32.txt)

**Comment by pkviet** [comment]
> [2020-12-02 13-43-32.txt](https://github.com/Andersama/obs-asio/files/5629667/2020-12-02.13-43-32.txt)

the plugin is not installed; I don't see it listed in the dll loaded

**Comment by pkviet** [comment]
> Thee are logs from that night.
> [2020-11-28 19-39-32.txt](https://github.com/Andersama/obs-asio/files/5629600/2020-11-28.19-39-32.txt)
> [2020-11-28 14-19-54.txt](https://github.com/Andersama/obs-asio/files/5629601/2020-11-28.14-19-54.txt)
> [2020-11-28 18-42-40.txt](https://github.com/Andersama/obs-asio/files/5629602/2020-11-28.18-42-40.txt)
> [2020-11-28 18-43-13.txt](https://github.com/Andersama/obs-asio/files/5629603/2020-11-28.18-43-13.txt)

the dll is loaded and i see that initially the UMC driver was loaded fine; try not to change anything.
The logs are with v3; retry with v2 to see if it makes any difference.
I'm wondering if asio4all is not making trouble. 
Does the Mackie work ? it's only the UMC ?

**Comment by nuthinfancy** [comment]
> > Thee are logs from that night.
> > [2020-11-28 19-39-32.txt](https://github.com/Andersama/obs-asio/files/5629600/2020-11-28.19-39-32.txt)
> > [2020-11-28 14-19-54.txt](https://github.com/Andersama/obs-asio/files/5629601/2020-11-28.14-19-54.txt)
> > [2020-11-28 18-42-40.txt](https://github.com/Andersama/obs-asio/files/5629602/2020-11-28.18-42-40.txt)
> > [2020-11-28 18-43-13.txt](https://github.com/Andersama/obs-asio/files/5629603/2020-11-28.18-43-13.txt)
> 
> the dll is loaded and i see that initially the UMC driver was loaded fine; try not to change anything.
> The logs are with v3; retry with v2 to see if it makes any difference.
> I'm wondering if asio4all is not making trouble.
> Does the Mackie work ? it's only the UMC ?

I don't use the Mackie any more. Do I even need the asio4all?

**Comment by pkviet** [comment]
> > > Thee are logs from that night.
> > > [2020-11-28 19-39-32.txt](https://github.com/Andersama/obs-asio/files/5629600/2020-11-28.19-39-32.txt)
> > > [2020-11-28 14-19-54.txt](https://github.com/Andersama/obs-asio/files/5629601/2020-11-28.14-19-54.txt)
> > > [2020-11-28 18-42-40.txt](https://github.com/Andersama/obs-asio/files/5629602/2020-11-28.18-42-40.txt)
> > > [2020-11-28 18-43-13.txt](https://github.com/Andersama/obs-asio/files/5629603/2020-11-28.18-43-13.txt)
> > 
> > 
> > the dll is loaded and i see that initially the UMC driver was loaded fine; try not to change anything.
> > The logs are with v3; retry with v2 to see if it makes any difference.
> > I'm wondering if asio4all is not making trouble.
> > Does the Mackie work ? it's only the UMC ?
> 
> I don't use the Mackie any more. Do I even need the asio4all?

uninstall it, I just want to make sure you didn't have any earlier settings of asio4all using the UMC, which could interfere

**Comment by nuthinfancy** [comment]
> > > > Thee are logs from that night.
> > > > [2020-11-28 19-39-32.txt](https://github.com/Andersama/obs-asio/files/5629600/2020-11-28.19-39-32.txt)
> > > > [2020-11-28 14-19-54.txt](https://github.com/Andersama/obs-asio/files/5629601/2020-11-28.14-19-54.txt)
> > > > [2020-11-28 18-42-40.txt](https://github.com/Andersama/obs-asio/files/5629602/2020-11-28.18-42-40.txt)
> > > > [2020-11-28 18-43-13.txt](https://github.com/Andersama/obs-asio/files/5629603/2020-11-28.18-43-13.txt)
> > > 
> > > 
> > > the dll is loaded and i see that initially the UMC driver was loaded fine; try not to change anything.
> > > The logs are with v3; retry with v2 to see if it makes any difference.
> > > I'm wondering if asio4all is not making trouble.
> > > Does the Mackie work ? it's only the UMC ?
> > 
> > 
> > I don't use the Mackie any more. Do I even need the asio4all?
> 
> uninstall it, I just want to make sure you didn't have any earlier settings of asio4all using the UMC, which could interfere

OK, I'll get rid of the un-needed stuff. I won't really be able to test it out till Fri and Sat. When I ran it last Sat, it was working all through setup and testing and of course as soon as I went live it had died.

**Comment by nuthinfancy** [comment]
pkviet--Thank you for your help

**Comment by MatterialTrash** [comment]
> > [2020-12-02 13-43-32.txt](https://github.com/Andersama/obs-asio/files/5629667/2020-12-02.13-43-32.txt)
> 
> the plugin is not installed; I don't see it listed in the dll loaded

Ok, iv now got it working! I think i needed the C++ Redist. Is there anything in the pipelines to make this Plugin compatible with StreamLabs in the future?

**Comment by pkviet** [comment]
> > > [2020-12-02 13-43-32.txt](https://github.com/Andersama/obs-asio/files/5629667/2020-12-02.13-43-32.txt)
> > 
> > 
> > the plugin is not installed; I don't see it listed in the dll loaded
> 
> Ok, iv now got it working! I think i needed the C++ Redist. Is there anything in the pipelines to make this Plugin compatible with StreamLabs in the future?

nope; streamlabs obs prevents plugins, they have to go through their marketplace.

**Comment by MatterialTrash** [comment]
> > > > [2020-12-02 13-43-32.txt](https://github.com/Andersama/obs-asio/files/5629667/2020-12-02.13-43-32.txt)
> > > 
> > > 
> > > the plugin is not installed; I don't see it listed in the dll loaded
> > 
> > 
> > Ok, iv now got it working! I think i needed the C++ Redist. Is there anything in the pipelines to make this Plugin compatible with StreamLabs in the future?
> 
> nope; streamlabs obs prevents plugins, they have to go through their marketplace.

Thats a crying shame! Thanks for your help. Have a good day. 👍

**Comment by nuthinfancy** [comment]
> > > > > Thee are logs from that night.
> > > > > [2020-11-28 19-39-32.txt](https://github.com/Andersama/obs-asio/files/5629600/2020-11-28.19-39-32.txt)
> > > > > [2020-11-28 14-19-54.txt](https://github.com/Andersama/obs-asio/files/5629601/2020-11-28.14-19-54.txt)
> > > > > [2020-11-28 18-42-40.txt](https://github.com/Andersama/obs-asio/files/5629602/2020-11-28.18-42-40.txt)
> > > > > [2020-11-28 18-43-13.txt](https://github.com/Andersama/obs-asio/files/5629603/2020-11-28.18-43-13.txt)
> > > > 
> > > > 
> > > > the dll is loaded and i see that initially the UMC driver was loaded fine; try not to change anything.
> > > > The logs are with v3; retry with v2 to see if it makes any difference.
> > > > I'm wondering if asio4all is not making trouble.
> > > > Does the Mackie work ? it's only the UMC ?
> > > 
> > > 
> > > I don't use the Mackie any more. Do I even need the asio4all?
> > 
> > 
> > uninstall it, I just want to make sure you didn't have any earlier settings of asio4all using the UMC, which could interfere
> 
> OK, I'll get rid of the un-needed stuff. I won't really be able to test it out till Fri and Sat. When I ran it last Sat, it was working all through setup and testing and of course as soon as I went live it had died.

I got rid of the asio4all and Mackie one. 2 nights, 5 hrs each and no issues. I would say that solved the problem
