### ISSUE TITLE
UMC404HD and Zoom H6

### ISSUE THREAD

**Issue by BCRandCo** [Andersama/obs-asio#72]
Both work beautifully with obs-asio and OBS. On my laptop (lenovo, WIN10 64-bit) I can use both simultaneously, but on my PC (also WIN 10 64-bit, lenovo), the behringer goes mute as soon as I plug the H6 into the PC. When I open the UMC/Asio control panel|Volume|Output everything is greyed out (which it isn't when the H6 isn't plugged in). In the Windows Sound|Recording|Behringer|Properties, the levels are fine. Any thoughts as to why this is happening?

**Comment by BCRandCo** [comment]
I think the problem may be solved. the H6 was at 44.1 Khz and the 404 at 48. Putting them both at 48 seems to have solved the problem. Does that sound likely to give a problem?

**Comment by pkviet** [comment]
cool if it's fixed your issue; it's really odd, no idea why it could occur. But hey I won't complain since it's fixed.
