### ISSUE TITLE
Audio feed becomes crackly if I open a browser/start a game while streaming

### ISSUE THREAD

**Issue by Starcoma** [Andersama/obs-asio#74]
**Describe the bug**
Yesterday (16th Dec) I updated OBS Studio to 26.1.0, since then the ASIO Input audio goes stuttery/crackly if I open up a web browser/start a game. The only way to resolve the audio problem is to close OBS and restart the stream.

I use a Behringer U-Phoria UMC202HD into Reaper and connect to the obs-asio plug-ing using Reapers ReaRoute.

I use the same plug-in for RPAN Studio, and the problem does not arise on that program. So my thinking is it has something to do with the compatibility between the updated OBS Studio and the obs-asio plug-in.

Furthermore, the audio that I am monitoring does NOT have the problem, eliminating any issues with my computer set up - only being heard via the viewers of the stream.

**To Reproduce**
1. Start stream with ASIO Input as a source.
2. Open a browser like Google Chrome, or start a game (for example I opened Marbles on Stream & Fallout 4)
3. Audience can now hear glitchy audio
4. Can only be resolved via restarting OBS Studio.

**Expected behavior**
Up until 16th Dec, the audio worked fine.

**Additional context**
All other audio from my computer, be it videos on Youtube, game audio, soundboard sounds, or iTunes music, all work fine while the audio from the ASIO Input is glitchy.

Here are some examples of the problem occuring in test streams:
[Example 1](https://www.twitch.tv/videos/840359919)
[Example 2](https://www.twitch.tv/videos/840363150)
[Example 3](https://www.twitch.tv/videos/840365002)

**Comment by Andersama** [comment]
Sorry, realized I should've added something to the issue template, which release of the plugin are you working with?

My immediate thought process here is it sounds like the audio thread(s) that are spun up for this plugin are ending up in contention with the newer apps you're launching. I'll have to go back over the code at some point. In the meantime, I'd suggest having as few other programs running, not exactly a solution, but if you find that helps please let me know.

**Comment by Andersama** [comment]
Is this still an issue?
