### ISSUE TITLE
connecting Allen & Heath Qu series via "USB 2.0 cable type A-B" to OBS on Win10 "PC": unreproducible sound loss of selected channels while live stream?

### ISSUE THREAD

**Issue by ALLENandHEATHqu24user** [Andersama/obs-asio#75]
Hi,
this is most likely NOT directly an issue with your ASIO-plugin! 
Up to now we use your 2.0.3 (considering 3.0.0?) with our Win10 PC (WDM driver V4.67.0; considering V4.86.0): We are dealing with the problem that from time to time while live streaming, the "sound connection" somewhere between mixer (Qu24; firmware1.93) and OBS "dies"!!!
The reason/trigger is up to now not clear to us and we have not been able to reproduce ad hoc! 
Up to now we were unable to dig out some solution thriving hint from the A&H forum ...

The only way which seems to work up to now as a fix: uninstall WDM driver & reinstall   

We use MIX7+8 (=stream-mix different then room-mix) selected as sources in OBS (26.0.2) 

Any idea if the USB connector selection on the mainboard or if the cable ("high qual shield or ferrit") can be the source of this pain? 

**Plugin Version**
- 2.0.3
- NDI-plugin

Qu USB control panel / WDM Driver Settings?:
ASIO™ Buffer Size (typically =512) and SAFE MODE

**Comment by Andersama** [comment]
Unless I'm mistaking what the acronym stands for WDM drivers should have absolutely nothing to do with asio. Your device should have an associated asio driver you're making use of. Unfortunately the stability of ASIO devices has in our experience been a complete toss up, when we were developing the plugin we were testing different devices. The plugin's largely a finished product which may need a few tweaks.

Consider building the bass asio branch #73 was a recent change someone made that's not been released yet.

**Comment by Andersama** [comment]
I will add I've owned a few audio devices whose usb components were not up to snuff and ended up forcing me to prefer the line in which generally suffers audio quality issues from the mother board sitting so close to the audio hardware. So I do understand that pain of having faulty audio hardware. If you do find out anything that may have to deal with software you may want to contact JUCE which is the library we used for the 2.0.3 version.
