### ISSUE TITLE
OBS 26.1.1 / ReaRoute in Reaper

### ISSUE THREAD

**Issue by BrentHathaway** [Andersama/obs-asio#76]
It appears that after updating to OBS 26.1.1 it killed the ReaRoute ASIO connection from Reaper. I updated your plugin to the latest, but am still having same problem. Please advise. It was working great!

**Comment by Andersama** [comment]
I don't really maintain plugins anymore, you're at risk when updating OBS of breaking abi changes, also pkv switched the underlying library being used. v3 is actually a significantly older plugin that was rebuilt, consider switching back to the older plugin / OBS.
