### ISSUE TITLE
Crashes when using it with any other application using AUDIO ASIO

### ISSUE THREAD

**Issue by tormyvancool** [Andersama/obs-asio#77]
Opening reaper 6.23 using REAROUTE
with version ASIO OBS 3.00, when in OBS I create an input, it crashes.
To create it, I need to have ONLY OBS activated. 
But then when I open the DAW it doesn't works always. Looks like a random work.

Moreover: whenever I want co make a tutorial showing the setup of any channel using ASIO, when OBS is running, it crashes.
This didn't occurred at all with previous version ov OBS ASIO

EDIT:
The version 3.0.0 results in continuous conflicts that are leading OBS to crash or to malfunctioning when it is sharing the audio resources.
Not possible to use them outside just a microphone connected to the interface.

**Comment by terrybritton** [comment]
Which interface?

**Comment by tormyvancool** [comment]
I did try form Line6 to Focusrite to Behringer UMC1820. The behavior is the same in all cases.

**Comment by gibbygano** [comment]
Also happening on Scarlett 18i8. 
Windows 10 Pro
Ryzen 3600x (if that helps at all).

**Comment by Andersama** [comment]
There's two versions really of the plugin that are released, one is based on the JUCE library, and one is based on the bassasio library. There's a bit of an issue that pkv named the release 3.0.0~, it's not necessarily better than 2.0.0~. In fact the bassasio library based one is one of the first implementations we had working, so it's extremely old. There was a recent patch made for devices that had issues at startup, it's not been built and released. I personally would HIGHLY recommend sticking w/ the JUCE library, it's been the most stable so far. If you didn't have issues before, I would not be suprised.

There's also a secondary issue that obs changes its plugin abi and breaks things. If you're not having significant issues w/ an older version of OBS I'd recommend reverting to whatever your previous install was. Sorry for the mess.

**Comment by tormyvancool** [comment]
Yes it works way better indeed. I just published a tutorial: [https://youtu.be/FCFXxQf-s6s](https://youtu.be/FCFXxQf-s6s). With the version 3.0.0 it's impossible to work in this way.
Thanks a zillion

**Comment by Andersama** [comment]
@tormyvancool no problem, I'm going to close this, but feel free to reopen or make another issue if you have any other problems.
