### ISSUE TITLE
Hotplugging support?

### ISSUE THREAD

**Issue by Wolbaz** [Andersama/obs-asio#79]
Is there any plan for hotplugging support? My audio interface output fails around once a day. I can fix it by replugging it in. If I'm streaming, that means shutting down the stream and restarting obs afterwards, or switching to the windows drivers.

**Comment by Andersama** [comment]
Another user appears to have similar issues, I don't remember writing the plugin to be hot-pluggable. Try both v2 and v3 and let me know if neither works, I might revisit this.

**Comment by pkviet** [comment]
I tried hotplugging with my DAW of choice (Reaper) and it didn't work. So imo it's unreasonable to expect us to support such a feature. Sorry.
Closing.
