### ISSUE TITLE
No ASIO output. 

### ISSUE THREAD

**Issue by SensArice** [Andersama/obs-asio#80]
No ASIO output. 

The lack of this feature doesn't make any sense for personal live streaming. 

Before I encounter it, I need to open an OBS and a cubase for live streaming. 

I need a low latency output so that I can replace the sound card's send and redundant DAW software. 

I think input can be done, and it is easy to make another one to lose.

**Comment by Andersama** [comment]
https://github.com/Andersama/obs-asio/wiki#limitations
