### ISSUE TITLE
OBS-Asio Stopped Working. SQ7 Mixer -> USB -> OBS-ASIO

### ISSUE THREAD

**Issue by ongxc** [Andersama/obs-asio#82]
Hi, we are facing this issue intermittently. Using asio-obs v2. Here's the log from OBS. Is there something that may trigger this as we only faced this once a while and we can't really reproduce the problem. 

> 
> 11:11:59.338: adding 64 milliseconds of audio buffering, total audio buffering is now 85 milliseconds (source: VideoCapture-Source)
> 11:11:59.338: 
> 11:13:19.153: User switched to scene 'Scripture'
> 11:13:23.498: adding 106 milliseconds of audio buffering, total audio buffering is now 192 milliseconds (source: VideoCapture-Source)
> 11:13:23.498: 
> 11:13:43.392: asio-input: Stopped (SQ ASIO Driver)
> 11:13:49.491: asio-input: Starting (SQ ASIO Driver)
> 11:14:11.536: User switched to scene 'Main Scene'
> 11:15:43.452: User switched to scene 'Raw Feed'
> 11:15:46.975: adding 64 milliseconds of audio buffering, total audio buffering is now 256 milliseconds (source: VideoCapture-Source)
> 11:15:46.975: 
> 11:15:58.760: [rtmp stream: 'adv_stream'] User stopped the stream
> 11:15:58.762: Output 'adv_stream': stopping
> 11:15:58.764: Output 'adv_stream': Total frames output: 133148
> 11:15:58.764: Output 'adv_stream': Total drawn frames: 133226 (133230 attempted)
> 11:15:58.764: Output 'adv_stream': Number of lagged frames due to rendering lag/stalls: 4 (0.0%)
> 11:15:58.766: warning: 2 frames left in the queue on closing

**Comment by pkviet** [comment]
a log of obs would help. If we don't know obs version, it's very hard to troubleshoot

**Comment by ongxc** [comment]
The full log is attached below. 

 OBS version: 26.1.0
 
 Symptom: Audio from Asio stopped working at 11:13:43.392. It happens randomly. 

[2021-01-10 10-01-31.txt](https://github.com/Andersama/obs-asio/files/6323210/2021-01-10.10-01-31.txt)

**Comment by pkviet** [comment]
There's no obvious reason I can spot. Try increasing the buffer of your device. This will help in general.

**Comment by Andersama** [comment]
@ongxc are you still having issues?

**Comment by ongxc** [comment]
Seems good for now. Thanks for the suggestion.

**Comment by Andersama** [comment]
@ongxc for future reference, the plugin does log device errors, so that sequence of stop / start was likely your device requesting a reset (not an error, but not in anyone's control, usually this happens when device settings are changed, but it could be something else).
