### ISSUE TITLE
Re-plugging the device while OBS is launched

### ISSUE THREAD

**Issue by MisterPiBody** [Andersama/obs-asio#83]
Using Helix LT with method V3
Everything works fine, but when I unplug and plug Helix back while OBS is still on, sound is not transferring anymore. It doesn't matter what settings i try to change in properties, switching ASIO types etc, no sound comes through. 
Only OBS restart works, not even removing this plugin from sources and adding it back.

Here's log
[2021-04-12 16-45-21.txt](https://github.com/Andersama/obs-asio/files/6297187/2021-04-12.16-45-21.txt)

**Comment by Andersama** [comment]
I don't remember ever making the plugin hot-pluggable. Don't do this, the restart works because the devices are relisted and initialized properly, by unplugging you're definitely going to create problems. In the meantime try version 2. If you can't hot-plug in both I might revisit this.

**Comment by MisterPiBody** [comment]
I'll take a look at look at V2 if something. 
Just thought about this in case something might happen during the stream like unexpected device unplugging by an accident for example.
Thanks for the reply!

**Comment by Andersama** [comment]
The only other solution but I doubt it could be automatic would be to add a button to essentially restart the device as though from scratch. TLDR: just in general, don't unplug devices when they're in use. Think of it like a hard-drive or ssd, they generally do not appreciate being disconnected.

**Comment by pkviet** [comment]
I tried hotplugging my asio device in Reaper and it did not work. Given such a reputable DAW doesn't support hotplugging, it seems unreasonable to expect us to support such a feature. Sorry.
Closing this.
