### ISSUE TITLE
obs-asio not picking up audio from Traktor

### ISSUE THREAD

**Issue by sensibleken1** [Andersama/obs-asio#84]
Hi there,

Im using a Traktor Kontrol S4 MK3 via Obs. Ive installed the plugin but no sound is coming through the ASIO Input capture. I can see they are talking to one another as when the buffer is changed in OBS it appears as the new value in the audio setup on traktor. I believe the root cause may be OBS Channel settings in the properties window. It detects the device but I cannot see what I am supposed to select in the OBS channel 1 dropdown, but none of the options result in obs picking up the audio. Is there something else I
![20210425_175502](https://user-images.githubusercontent.com/83178937/116003665-cfb1b580-a5f6-11eb-8f0b-94baca767b90.jpg)
 need to do? Sorry for the photo over a screenshot, long story.
Thanks
Ken

**Comment by Andersama** [comment]
Pick the channels that you're looking to capture off your device. By we have the plugin use muted channels, that definitely will not work if you're looking to capture any audio. @pkviet I added a timestamp logger for this if you want to rebuild.

**Comment by sensibleken1** [comment]
Thanks for getting back to me. Ill fiddle with it and report back in case others need to see the answer.

**Comment by Andersama** [comment]
My best guess from what I can see on amazon is that D-L / D-R is likely the xlr mic jack. I'd mess with any / all the gain knobs and try to put them to max, don't know your setup, it might be just that low. If you add a spectrogram / spectrograph vst that's a decent debugging tool. I never added a bytes/samples written metric, but now that makes more sense to have.

**Comment by sensibleken1** [comment]
Thanks for getting back to me, much appreciated. It wasn't the gain though, may have annoyed some neighbours with that attempt, lol. 

So the controller has 4 channels. Two of which are playing the audio I'm trying to capture in obs and stream. The setup in the trakor application for these decks is below:
![image](https://user-images.githubusercontent.com/83178937/116902927-aa92f780-ac33-11eb-95e2-7f7a1cc1e8cf.png)

Ive tried the below settings, but neither works:

![image](https://user-images.githubusercontent.com/83178937/116903165-f34ab080-ac33-11eb-843c-49083aae144c.png)
 and 
![image](https://user-images.githubusercontent.com/83178937/116904492-abc52400-ac35-11eb-8fef-c7322f19789a.png)

Any ideas?

**Comment by Andersama** [comment]
Well there's a couple of ideas I have, one asio drivers tend to be written where only one application can use them at a time. It might that your software that you screen capped is creating issues. You also just made it sound as though the audio you're trying to capture is a software mix, usually ASIO drivers are for hardware channels, I've only run into a few which have a loopback channel or spare ones to mix with. If you're mixing and editing in another daw, you can work around that restriction if your daw has its own virtual asio device. Although it's not clear to me if that application is your control panel or something like that, I vaguely remember audio getting muted when control panels are opened. Try closing other applications that are using that device if they're not needed.

Can I have you confirm what version of the plugin and OBS you're on? I can tell from those screenshots it's the Juce based one. A screenshot of a spectrogram would definitely help to confirm it's not just a volume issue. If @pkviet  gets around to rebuilding the plugin, we can poke around further to see if the device ever became active. Might not need that if you can provide a log.

**Comment by Andersama** [comment]
Feel free to reopen, I'm going to take this as another device which doesn't work.
