### ISSUE TITLE
There is no ASIO section in OBS

### ISSUE THREAD

**Issue by omerdn** [Andersama/obs-asio#85]
**Plugin Version**
The latest one v3.1.0

**Describe the bug**
I installed the plugin after installing the visual studio etc. But when i want to add asio input in obs, there is no asio section to add.
[log file.txt](https://github.com/Andersama/obs-asio/files/6380448/log.file.txt)

**Screenshots**
![resim](https://user-images.githubusercontent.com/82974403/116153208-a163d100-a6ef-11eb-849b-2c3c2a1c645b.png)

**Comment by pkviet** [comment]
V3.1 is for obs 27+.
You are on 26.1.1 ... Install obs-asio 2

**Comment by omerdn** [comment]
Oh sorry my fault. Thanks
