### ISSUE TITLE
No audio interface output listed

### ISSUE THREAD

**Issue by CemboCembus** [Andersama/obs-asio#86]
Hi, I'm Cem

I tried to use asio-obs 3.1.0 with OBS v27 and 2.0.3 with OBS v26. I created asio input capture in OBS and selected my audio interface asio driver which is Behringer UMC404HD. The problem is obs channel listing only show inputs of my audio interface. In order to get audio from Ableton live 11 to OBS I need to be able to select my audio interface's audio outputs as obs channel. But no luck. Only audio inputs are shown and I cannot route audio from Ableton Live 11 to OBS

Thank you.

**Comment by Andersama** [comment]
See: https://github.com/Andersama/obs-asio/wiki#limitations

No problem.
