### ISSUE TITLE
Can you add TASCAM Series 102i and 208i to the supported devices?

### ISSUE THREAD

**Issue by WhiteWolfofTyr** [Andersama/obs-asio#89]
Hey guys.

Thanks for making this, but I have notices that since you moved away from the bassasio library, my Tascam Series 208i is no longer functioning. Also, the ASIO file types don't show up in my sources. I don't know if I am doing something wrong, but I don't even have the capability to select it unless I use an older version of the plugin.

**Comment by Andersama** [comment]
The latest release is only for the latest release of obs. If the bass asio plugin works, and you just tried the newest juce based one, that could easily be why. Other than that, feel free to add the devices to the list yourself.
