### ISSUE TITLE
Having a slight delay while monitoring audio through OBS

### ISSUE THREAD

**Issue by RoyZ7** [Andersama/obs-asio#93]
Hi,

I got a slight delay, somewhere around 100-200ms, I'm using the latest version which uses JUCE.

I have two audio interfaces and they both give about the same delay.

I don't have any delay if I listen to the monitoring from the interface or when I monitor the audio while using another program like "Cakewalk", it's only when I monitor the audio through OBS I get this delay. 

I've tried changing every possible setting on my "Roland Quad Capture" driver software and on my "Behringer UMC204HD" driver software, some changes made the delay smaller but the smallest I get is about 100-200ms as I've mentioned.

Is there anything I could try to make the delay smaller?

Thanks a lot for this plugin and your help, it's much appreciated. 

Roy.

**Comment by AronHetLam** [comment]
You can offset it in OBS itself, so that it matches the video. 
On your audio source, click the gear icon, and select "Advanced Audio Properties" (It has another name in earlier versions)
![image](https://user-images.githubusercontent.com/5564813/121143162-0822f100-c83d-11eb-83b9-d53503e37fb7.png)

Then adjust the offset in ms for the audio input in need.
![image](https://user-images.githubusercontent.com/5564813/121143529-6f40a580-c83d-11eb-8463-a0c40afb534f.png)

**Comment by RoyZ7** [comment]
Thanks a lot @AronHetLam, Sorry for the late reply, I was testing it and it doesn't work for monitoring.

I've also [read here](https://obsproject.com/forum/threads/audio-sync-offset-not-working.125660/) that it doesn't work for monitoring purposes, just for recording/streaming purposes.

I was thinking that the whole advantage using ASIO would be the very low latency and it should've worked for monitoring too no? Is there another limitation? 

Thanks a lot,

Roy.

**Comment by AronHetLam** [comment]
Monitoring and delay in those settings is most likely more dependant on OBS than this plugin.

**Comment by RoyZ7** [comment]
@AronHetLam So you mean that OBS is the cause of the delay? 

Can you confirm @Andersama ?  Is there anything that could be done about it if so?

**Comment by AronHetLam** [comment]
I might have missed an important point. Is it not enough that the audio and video is in sync in the OBS output (Stream/Recording)?

What I meant with

> Monitoring and delay in those settings is most likely more dependant on OBS than this plugin.

Is that those screenshots posted earlier are OBS's tools for syncing audio and video in the output. 

What causes the initial delay probably isn't OBS, but I don't know if it's this plugin, or something else.

**Comment by RoyZ7** [comment]
Thanks @AronHetLam, Yeah, monitoring is important too as you'd want to hear how you sound in real-time as well,
I suspect the delay might be coming from the JUCE library that's being used.

That's why I was thinking to ask @Andersama If there might be any options that could be exposed from JUCE or anything like that, that could help minimizing the delay since I have two audio interfaces and the delay doesn't happen while using a DAW, but  does happen using the plugin in OBS..

Thank you 🙏

Roy.

**Comment by pkviet** [comment]
The monitoring delay has nothing to do with juce. It comes from obs monitoring system which relies on wasapi on windows. It adds at least 100 ms. That's the delay you hear. There's no such delay on the stream or recording though. It's only in the monitoring subsystem. You'd be better off with using the direct monitoring which is often provided by asio sound cards.
