### ISSUE TITLE
Use OBS Asio on a Mac

### ISSUE THREAD

**Issue by apacha** [Andersama/obs-asio#94]
Hi, I have a Zoom L-12 and unfortunately, OBS only recognized the entire device without giving me any control on which channels to receive from. I was hoping that with this addon, I could select Channels 13+14 (Stereo Output), however, I'm on Mac. Is there a way how to install this plugin on a Mac? Or is there similar software available that could to the trick?
Thanks a lot in advance.

**Comment by Andersama** [comment]
ASIO is as far as I'm aware only supported by windows, I've never bothered to attempt to build the plugin for anything else. *Technically* this plugin is built on Juce, and *technically* Juce supports all the native audio engines available on the operating systems, but that'd be redundant at least for OBS. If you're not able to select audio channels for your device you're kind of stuck. I wrote this specifically to deal with the exact same issue you're having, except I'm on windows.

Your best bet is to do a bit of messy audio routing if at all possible, I have no idea what the Mac environment is like. I'd assume there's audio software that could do what you want. If you've got software that lets you select your audio channels check to see if it can output an audio stream, you can definitely capture stuff going over the web.

**Comment by apacha** [comment]
Thanks a lot for the explanation. I was afraid that this would be the case. I will use a PC then.
For Mac there are two options I found: Jack and Loopback (https://rogueamoeba.com/loopback/). Jack had issues with the device and Loopback works, but costs 100$+, which is way too much a for a small utility to route a bit of audio on a Mac.

Thanks anyway for your help.
