### ISSUE TITLE
Plugin crashes when selecting ASIO device on OBS 27 >

### ISSUE THREAD

**Issue by prgmitchell** [Andersama/obs-asio#95]
Before posting an Issue, make sure that:
- you've read the wiki especially the Install and Usage section, the Troubleshooting section, the Capturing mixes section.
- you've researched the issues to find if there aren't similar issues which have been posted already.
- have an obs log ready (obs-studio : help menu > log > see current log)

**Plugin Version**
Which release of the plugin are you using?
Most recent

**Describe the bug**
Doesn't generate a crash log, downgrading to 26.1.1 resolves, crashes OBS when ASIO device is selected.

**To Reproduce**
1. Add ASIO input
2. Select ASIO device
3. OBS not responding, have to close in task manager.

**Expected behavior**
Um, just for it to work :)

**Screenshots**

**Additional context**

**Comment by Andersama** [comment]
"Most recent" doesn't exactly tell me what you're working with. There are abi issues between major obs versions, it sounds like you have one of plugins built against 26 installed.

**Comment by prgmitchell** [comment]
I did not even see the JUCE version, my mistake! Problem resolved, thank you!

Sent from my iPhone

On Jun 27, 2021, at 5:26 PM, Alex Anderson ***@***.***> wrote:

﻿

"Most recent" doesn't exactly tell me what you're working with. There are abi issues between major obs versions, it sounds like you have one of plugins built against 26 installed.

**Comment by Andersama** [comment]
No problem.
